name: Test Windows Binary
on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - "adr/**"
      - "docs/**"
      - "CODEOWNERS"

permissions:
  contents: read

# Abort prior jobs in the same workflow / PR
concurrency:
  group: e2e-windows-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Optimize caching
        run: echo C:\Program Files\Git\usr\bin>>"%GITHUB_PATH%"
        shell: cmd

      - name: Setup golang
        uses: ./.github/actions/golang

      - name: Run Windows unit tests
        run: make test-unit
        shell: pwsh

      - name: Build Windows binary and zarf packages
        uses: ./.github/actions/packages
        with:
          init-package: "false"
          os: windows
          shell: pwsh

      - name: Run windows E2E tests
        run: make test-e2e-without-cluster
        shell: pwsh
